### ISSUE TITLE
학습 결과 (1/17 ~ 1/21) 로그 확인 요청

### ISSUE THREAD

**Issue by hongyongje** [Kisane-Project/object-detection#2]
[log_20230125.txt](https://github.com/Kisane-Project/object-detection/files/10494983/log_20230125.txt)

1/17~ 1/21 약 3일 18시간 30분 동안 학습 완료한 로그입니다.

gist 에서 생성했던 결과 수치와 차이가 있는 지 확인 요청 드립니다.

1) AP 차이 여부
2) 학습 시간 차이

**Comment by tjdhg456** [comment]
안녕하세요.

1. 정상적으로 학습 된 것 같습니다.
2. 학습 시간은 차이가 있으나, 사용한 GPU 대수에 따른 차이여서 큰 문제는 없을 것 같습니다.

**Comment by yjhong-kisane** [comment]
2 번 항목 관련해서,
저희 학습 서버의 H/W 스펙을 얼마나 높여야 할지 참고하기 위해
gist 에서는 학습 시간이 얼마나 소요 되었는지 요청 드리겠습니다.

**Comment by tjdhg456** [comment]
안녕하세요.

GPU GTX 3090 4대 활용해서 2일 소요 되었습니다.

하지만, 현재는 주어진 4대 GPU를 모두 100% 활용해서 학습 한 것은 아닙니다.  

속도를 올리기 위해서는 batch_size 파라미터를 조정하면 되는데요.
GPU 4대를 사용하면 사용할 수 있는 전체 메모리가 4배 증가하므로 batch size를 1대 사용했을 때 보다 4배 만큼 늘릴 수 있고, 이에 비례해서 속도도 증가합니다.

하지만, batch size를 증가시키면 그에 따른 다른 모델들의 하이퍼 파라미터도 같이 변경해주어야 해서 실험 과정이 필요합니다. 해당 부분은 추후 규칙화 시켜서 말씀드리겠습니다.

비슷한 규모의 데이터 셋을 학습할 때 경험으로 보면, RTX 3090 4대를 100% 활용했을 때 기산 전자 데이터 셋은 24시간 내외로 학습할 수 있을 것으로 보입니다.

**Comment by tjdhg456** [comment]
그리고, 추론 모델 요청과 관련해서는,

1. (성능 평가용) 해당 시스템 내에서 **특정 폴더**에 이미지와 정답 라벨을 저장하고, 해당 폴더의 경로를 입력 받아 AP를 추출할 수 있는 코드를 제작하겠습니다.
2. (실제 추론용) 실제 추론시에는 정답 라벨이 없으므로, 한 개의 이미지 파일의 경로, 혹은 복수의 이미지가 저장되어있는 폴더의 경로를 입력받으면 추론 결과를 json 형식 혹은 txt 형식으로 저장할 수 있는 코드를 제작해 드리겠습니다.

**Comment by kyshin-kisane** [comment]
안녕하세요, 기산전자 신광용입니다.
지금은 모델의 성능을 확인하는 과정에서는 특정 파일 위치에 결과를 입출력하는 형태는 맞지만, 
현재, APL을 개발하고 있는 단계이기 때문에, 파일 단위 (형태)가 아닌,
Python 기반으로 취득된 영상을 전달하는 프로토콜 (방식, 예를들어 TCP/IP 혹은 다른 IPC 기법을 활용)을 통해 전달하고, Detection 및 Inference 정보를 전송 받을 수 있는 형태로 구성 및 해당 방식을 공유되어야 할 것 같습니다.
혹시, 추가적인 설명이 필요하다면, 홍용제 책임이랑 유선으로 논의해보는것도 좋을것 같습니다.

**Comment by tjdhg456** [comment]
안녕하세요.

네, 메일로 보내주신 그림을 참조해보면,

1. 영상 화면 조작 모듈에서 촬영 버튼을 클릭
2. 카메라 모듈에서 이미지 촬영
3. 촬영된 이미지를 딥러닝 추론 모듈로 전달
4. 딥러닝 추론 결과를 다시 화면 조작 모듈로 전달

이 순서가 될 것 같습니다.

그러면 저희가 3, 4번 과정에서 tcp 프로토콜을 통해서 1. 이미지 수신 / 2. 결과 송신을 할 수 있도록 하면 될 것 같은데, 이때 어떤 프로토콜 (Ip / port / 송수신 데이터 포맷)로 진행하면 될지 알려주시면 맞춰서 업로드 하겠습니다.
