### ISSUE TITLE
AI Scanner 추론 모듈 TCP/IP 통신 프로토콜 설계

### ISSUE THREAD

**Issue by yjhong-kisane** [Kisane-Project/object-detection#3]
AI Scanner Application 관계도

![Image](https://user-images.githubusercontent.com/121783905/215498352-3f5a2e29-3520-4277-9d56-6c018270e39c.png)

상기 2와 3간 TCP/IP 통신 설계

    TCP 서버는 하기와 같이 설정
    Port : 9000
    IP : 127.0.0.1

    (추후) N개의 Client가 Server에 접속하여 추론을 할 수 있는 방식
	* 멀티 스레드 소켓 서버로 구현

![image](https://user-images.githubusercontent.com/121783905/215499313-6d7d6ec1-9451-45d6-9e0e-00dca0a0db68.png)

통신 프로토콜 문서 : [AI_Scanner_통신Protocol_20230130.xlsx](https://github.com/Kisane-Project/object-detection/files/10536358/AI_Scanner_.Protocol_20230130.xlsx)

상기 내용 검토 요청드립니다.

**Comment by tjdhg456** [comment]
안녕하세요.

RestAPI 기반으로 저희 모듈 API를 설계하기로 했고 (통신은 TCP 구조와 동일 합니다), 
기본 딥러닝 모듈들을 계획대로 먼저 구축한 후 API 제작을 진행하는 것으로 교수님께 전달 받았습니다.

그래서, 해당 API 부분은 사전 계획대로 1분기 (~3월) 딥러닝 모듈 제작이 끝난 이후 RestAPI 시스템 제작을 진행할 때 고려하겠습니다.

**Comment by kyshin-kisane** [comment]
안녕하세요, 신광용입니다.

RestAPI 관련해서 설계할 내용을 간략히 전달해주시면, 저희쪽에서 검토해서 RestAPI가 적용될수 있도록 미리 준비하겠습니다.
또한, 온라인 미팅 및 메일로 요청드렸던 것처럼, 전달해주신 모델을 기반으로 간략하게 인식 및 검출 성능을 테스트 볼 수 있는 추론기를 전달받고 싶은데요.  검토 요청드립니다.
